name: Java CI with Maven
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Cache NVD database
      - name: Cache Dependency-Check NVD
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: nvd-${{ runner.os }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # Test with coverage
      - name: Build and test with coverage
        run: mvn clean verify
      # Deploy JaCoCo HTML report to GitHub Pages
      - name: Deploy JaCoCo report to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/jacoco
      # Print the URL to access the report
      - name: Show coverage report URL
        run: |
          echo "Coverage report URL: https://Ollie1994.github.io/health_care_ab_server/index.html"
      # Security scan of dependencies.

      - name: Security scan
        run: mvn org.owasp:dependency-check-maven:check \
          -DnvdApiKey=${{ secrets.NVD_API_KEY }} \
          -DfailBuildOnCVSS=7
      # Upload dependency check report
      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html