name: Java CI with Maven
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Cache NVD database
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dc-${{ runner.os }}-${{ hashFiles('pom.xml') }}
          restore-keys: dc-${{ runner.os }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # Test with coverage
      - name: Test with coverage (fail < 80%)
        run: mvn test jacoco:report jacoco:check -Djacoco.check.rule.minimum=0.80
      # Security scan of dependencies.
      - name: Security scan
        run: mvn org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=7
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      # Upload dependency check report
      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html